// Code generated by MockGen. DO NOT EDIT.
// Source: packer.go
//
// Generated by this command:
//
//	mockgen -source=packer.go -destination=packer_repository_mock_test.go -package=packer
//

// Package packer is a generated GoMock package.
package packer

import (
	context "context"
	reflect "reflect"

	domain "github.com/Je33/packager/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// PackCreate mocks base method.
func (m *MockRepository) PackCreate(ctx context.Context, pack *domain.Pack) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackCreate", ctx, pack)
	ret0, _ := ret[0].(error)
	return ret0
}

// PackCreate indicates an expected call of PackCreate.
func (mr *MockRepositoryMockRecorder) PackCreate(ctx, pack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackCreate", reflect.TypeOf((*MockRepository)(nil).PackCreate), ctx, pack)
}

// PackDelete mocks base method.
func (m *MockRepository) PackDelete(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackDelete", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// PackDelete indicates an expected call of PackDelete.
func (mr *MockRepositoryMockRecorder) PackDelete(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackDelete", reflect.TypeOf((*MockRepository)(nil).PackDelete), ctx, uid)
}

// PackGetAll mocks base method.
func (m *MockRepository) PackGetAll(ctx context.Context, params domain.PackGetAllRequest) ([]*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackGetAll", ctx, params)
	ret0, _ := ret[0].([]*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PackGetAll indicates an expected call of PackGetAll.
func (mr *MockRepositoryMockRecorder) PackGetAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackGetAll", reflect.TypeOf((*MockRepository)(nil).PackGetAll), ctx, params)
}

// PackGetOne mocks base method.
func (m *MockRepository) PackGetOne(ctx context.Context, uid string) (*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackGetOne", ctx, uid)
	ret0, _ := ret[0].(*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PackGetOne indicates an expected call of PackGetOne.
func (mr *MockRepositoryMockRecorder) PackGetOne(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackGetOne", reflect.TypeOf((*MockRepository)(nil).PackGetOne), ctx, uid)
}

// PackUpdate mocks base method.
func (m *MockRepository) PackUpdate(ctx context.Context, pack *domain.Pack) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackUpdate", ctx, pack)
	ret0, _ := ret[0].(error)
	return ret0
}

// PackUpdate indicates an expected call of PackUpdate.
func (mr *MockRepositoryMockRecorder) PackUpdate(ctx, pack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackUpdate", reflect.TypeOf((*MockRepository)(nil).PackUpdate), ctx, pack)
}
