version: "2"
run:
  tests: true
linters:
  enable:
    - misspell
    - unconvert
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/Je33/packager
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
