package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"

	"github.com/Je33/packager/internal/domain"
)

// PackDelete is the resolver for the packDelete field.
func (r *mutationResolver) PackDelete(ctx context.Context, input domain.PackDeleteRequest) (*domain.PackDeleteResponse, error) {
	return r.packer.Delete(ctx, input)
}
