package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"

	"github.com/Je33/packager/internal/domain"
)

// PackGetAll is the resolver for the packGetAll field.
func (r *queryResolver) PackGetAll(ctx context.Context, input domain.PackGetAllRequest) (*domain.PackGetAllResponse, error) {
	return r.packer.GetAll(ctx, input)
}
