package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"

	"github.com/Je33/packager/internal/domain"
)

// PackUpdate is the resolver for the packUpdate field.
func (r *mutationResolver) PackUpdate(ctx context.Context, input domain.PackUpdateRequest) (*domain.PackUpdateResponse, error) {
	return r.packer.Update(ctx, input)
}
